wultra/powerauth-webflow

powerauth-webauth-client/src/main/resources/application.properties, powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/configuration/OAuth2AuthorizationServerConfiguration.java
Authorization server data moved to JDBC data source, if we want to keep something in memory (e.g. tokens), we can revert this part
DDL script is below - do we want to add run the DDL using spring boot if tables don't exist?
```sql
create table oauth_client_details (
client_id VARCHAR(256) PRIMARY KEY,
resource_ids VARCHAR(256),
client_secret VARCHAR(256),
scope VARCHAR(256),
authorized_grant_types VARCHAR(256),
web_server_redirect_uri VARCHAR(256),
authorities VARCHAR(256),
access_token_validity INTEGER,
refresh_token_validity INTEGER,
additional_information VARCHAR(4096),
autoapprove VARCHAR(256)
);
create table oauth_client_token (
token_id VARCHAR(256),
token LONG VARBINARY,
authentication_id VARCHAR(256) PRIMARY KEY,
user_name VARCHAR(256),
client_id VARCHAR(256)
);
create table …
```
=> Fix #15 - Implement persistent storage of OAuth 2 clients in DB

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/enumeration/OperationRequestType.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/GetPendingOperationsRequest.java, powerauth-nextstep/pom.xml, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/OperationHistoryRepository.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/OperationRepository.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/StepDefinitionRepository.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationHistoryEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/StepDefinitionEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/IdGeneratorService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-nextstep/src/main/resources/application.properties, powerauth-webauth-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/method/init/ApiController.java, powerauth-webauth-authentication/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/service/AuthenticationManagementService.java, powerauth-webauth-docs/sql/mysql/create_schema.sql, powerauth-webauth-docs/sql/mysql/initial_data.sql, powerauth-webauth/src/main/js/components/operation.js, powerauth-webauth/src/main/js/dispatcher/dispatcher.js, powerauth-webauth/src/main/resources/static/resources/messages_cs.properties, powerauth-webauth/src/main/resources/static/resources/messages_en.properties
Note that the issue-20 branch is built on top of the issue-19 branch, so this pull request contains both issue-19 and issue-20 implementations.
This implementation added querying of pending operations for given userId on the Next Step server.
Remarks:
* Currently no ordering is performed, operations are returned "as they come". I can order the operations in case it would be useful.
* I can also filter out expired operations - right now all operations are returned.
=> Implementation of Issue 20 - Create NextStep method to obtain all pending operations for given "userId"

powerauth-webauth-authentication-mtoken/pom.xml, powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/MobileTokenController.java, powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/controller/MessageController.java, powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/model/request/WebSocketRegistrationRequest.java, powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/model/response/MobileTokenInitResponse.java, powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/model/response/WebSocketAuthorizationResponse.java, powerauth-webauth-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/mtoken/model/response/WebSocketRegistrationResponse.java, powerauth-webauth/package.json, powerauth-webauth/pom.xml, powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/configuration/SecurityConfiguration.java, powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/configuration/WebSocketConfiguration.java, powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/configuration/WebSocketSecurityConfiguration.java, powerauth-webauth/src/main/js/actions/tokenActions.js, powerauth-webauth/src/main/js/components/token.js, powerauth-webauth/src/main/js/websocket-client.js
I implemented the first version of WebSocket notifications for the mobile token step.
Remarks:
* 3s polling is still used as a fallback for authorization, so even if the message could not be sent from the server to the client, it's no big deal.
* WebSockets are used to notify the UI (the Token component) so that authenticate() method can be dispatched immediately, authentication still works the same as before but its trigger is faster in mobile token step thanks to WebSocket notification.
How does it work:
* During the /init phase of mtoken step a MobileTokenInitResponse object is returned which contains a generated webSocketId used during the WebSocket communication.
* The webSocketId is generated as an MD5 hash of operationId, so that we don't send operationId to the UI, however we can …
=> Implementation of #42 - Let's use WebSockets for push token refresh

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java
Added sorting by priority
Step definitions are checked for duplicate priorities
=> Fix #30: Priority is ignored in Next Step step definitions

powerauth-webauth-authentication/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/controller/AuthMethodController.java
Authorization response is derived from operation detail if possible, only when it cannot be derived, authorize() method is called
=> Fix #44: The last authMethod/authResult is shown twice in operation history

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/AuthMethodDetail.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetAuthMethodsResponse.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/AuthMethodEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthMethodService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-webauth-authentication/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/controller/AuthMethodController.java, powerauth-webauth-docs/sql/mysql/create_schema.sql, powerauth-webauth-docs/sql/mysql/initial_data.sql, powerauth-webauth/src/main/resources/static/resources/messages_cs.properties, powerauth-webauth/src/main/resources/static/resources/messages_en.properties
Note that the pull request contains a commit from #69 to avoid a merge conflict (both commits change the StepResolutionService class). I suggest you merge pull request #69 first and then this one.
The change adds legitimity checks to the update of a NS operation.
Additionally, I fixed a mistake we made when merging fix of #44 - the deriveAuthorizationResponseFromOperationDetail() method needs to be called before authorize() and it makes sense to call it only when userId is known. I found out about this problem thanks to the legitimity checks.
=> Fix #45: Check legitimity of update calls in Next Step server

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/AuthMethodDetail.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/CreateOperationRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetAuthMethodsResponse.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/AuthMethodEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthMethodService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-webauth-authentication/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/controller/AuthMethodController.java, powerauth-webauth-client/src/main/java/io/getlime/security/powerauth/app/webauth/demo/controller/HomeController.java, powerauth-webauth-docs/sql/mysql/create_schema.sql, powerauth-webauth-docs/sql/mysql/initial_data.sql, powerauth-webauth/src/main/resources/static/resources/messages_cs.properties, powerauth-webauth/src/main/resources/static/resources/messages_en.properties
Note that this pull request contains pull requests #69 and #71 because of potential merge conflicts.
It should be possible to use a custom operationId now when creating an operation.
=> Fix #68: Allow custom operation ID while creating operation

powerauth-bank-adapter-client/src/main/java/io/getlime/security/powerauth/lib/bankadapter/client/BankAdapterClient.java, powerauth-bank-adapter-model/pom.xml, powerauth-bank-adapter-model/src/main/java/io/getlime/security/powerauth/lib/bankadapter/model/request/CreateSMSAuthorizationRequest.java, powerauth-bank-adapter/src/main/java/io/getlime/security/powerauth/lib/bankadapter/controller/SMSAuthorizationController.java, powerauth-bank-adapter/src/main/java/io/getlime/security/powerauth/lib/bankadapter/repository/model/entity/SMSAuthorizationEntity.java, powerauth-bank-adapter/src/main/java/io/getlime/security/powerauth/lib/bankadapter/service/OperationFormDataService.java, powerauth-bank-adapter/src/main/java/io/getlime/security/powerauth/lib/bankadapter/validation/CreateSMSAuthorizationRequestValidator.java, powerauth-bank-adapter/src/main/resources/application.properties, powerauth-nextstep/src/main/resources/application.properties, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java, powerauth-webflow-client/src/main/resources/application.properties, powerauth-webflow-docs/sql/mysql/create_schema.sql, powerauth-webflow/src/main/resources/application.properties
Note that this change contains DDL changes in ba_sms_authorization table.
Full change log:
* Fix #96: Use formData for generating authorization SMS OTP text
* Updated ba_sms_authorization table and related entity not to contain data, just reference an operation instead
* Finished migration to utf8mb4 character encoding for MySQL
* Switched to TEXT data type for columns where we do not control text size (and it may be bigger thanks to utf8mb4)
=> Fix #96: Use formData for generating authorization SMS OTP text

powerauth-bank-adapter/src/main/java/io/getlime/security/powerauth/lib/bankadapter/controller/SMSAuthorizationController.java, powerauth-bank-adapter/src/main/java/io/getlime/security/powerauth/lib/bankadapter/repository/model/entity/SMSAuthorizationEntity.java, powerauth-webflow-docs/sql/mysql/create_schema.sql, powerauth-webflow-docs/sql/oracle/create_schema.sql
Again, a small DDL change is present.
=> Fix #115: Store `salt` from DataDigest object when generating SMS OTP

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java
Double cancelations are now supported. All additional cancellation requests are recorded in operation history and the operation remains in FAILED/CANCELED state.
=> Fix #102: Clicking twice on Cancel leads to a 500 error

powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/service/DataAdapterService.java
UserId is now same as username in default DA implementation.
=> Fix #134: Default implementation of Data Adapter user authentication should return same userId as username

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow/src/main/js/actions/operationReviewActions.js, powerauth-webflow/src/main/js/actions/tokenAuthOfflineActions.js, powerauth-webflow/src/main/js/actions/tokenAuthOnlineActions.js, powerauth-webflow/src/main/js/components/app.js, powerauth-webflow/src/main/js/components/tokenAuth.js, powerauth-webflow/src/main/js/components/tokenAuthOffline.js, powerauth-webflow/src/main/js/components/tokenAuthOnline.js, powerauth-webflow/src/main/js/reducers/dispatchingReducer.js
This change is quite complex and will require testing - we should check whether Mobile Token online mode and offline modes still work same as before and it is possible to use online mode on the offline mode page without any side effects.
Changelog:
- Both online and offline modes are now combined in the UI, in the offline screen user can perform online Mobile Token authorization
- SHOW_SCREEN_QR_CODE was replaced by SHOW_SCREEN_TOKEN, Mobile Token is now one UI component with 2 sub-components (online and offline)
- Endpoint '/api/auth/qr' renamed to '/api/auth/token/offline'
- Better names for online and offline mode classes, components and methods to avoid confusion after combining both modes
- Updated logic in MobileToken web controller for resolving history which takes into account …
=> Fix #117: Support switch from offline mode back to online mode

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/CancelOperationFailedException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/InvalidActivationException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/InvalidRequestObjectException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/PendingOperationListFailedException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/PushRegistrationFailedException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/QRCodeExceptionResolver.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/SignatureVerificationException.java
Partial resolution for #145: Use Error class for Exceptions in Mobile API
=> Fix #136: Verify activationId in mobile API requests of Mobile Token step

powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java, powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties, powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties
All cases when operation is not available (is null) should be handled now
=> Fix #101: NullPointerException at mobile token /authenticate method

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/OperationExpiredException.java, powerauth-webflow/src/main/js/actions/smsAuthActions.js, powerauth-webflow/src/main/js/actions/tokenAuthOfflineActions.js, powerauth-webflow/src/main/js/actions/tokenAuthOnlineActions.js, powerauth-webflow/src/main/js/actions/usernamePasswordAuthActions.js
There were three problems:
* Obsolete strings for detecting timeout in the UI causing the UI not to respond to operation expiration
* Mobile API could confirm expired operations - authentication is not done at this point, so expiration needs to be checked explicitly
* Added the newer AUTH_METHOD_FAILED AuthStepResult for consistency when resolving the next step
=> Fix #180: Mobile token authentication does not expire

powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/entity/DataAdapterError.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/api/DataAdapter.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/AuthenticationController.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/BankAccountController.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/FormDataChangeController.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/OperationChangeController.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/SMSAuthorizationController.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/exception/DataAdapterRemoteException.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/exception/DefaultExceptionResolver.java, powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties, powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties
I added the DataAdapterRemoteException. The error message is not propagated into user interface (a more generic remote error text is displayed), however the exception is logged.
=> Fix #200: Data Adapter service must account for networking errors

powerauth-webflow-docs/sql/oracle/create_schema.sql
Let's use BLOB instead of RAW(16), it resolves the issue I had. Furthermore we use BLOB in many other columns, so it is better for consistency.
=> Fix #210: Error when reading SMS salt with Oracle

powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/ApiController.java, powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/model/response/InitOperationResponse.java, powerauth-webflow/src/main/js/actions/startHandshakeActions.js
Allow null operation in INIT authentication method for default operations.
Transfer operation hash to the client for default operations which are initialized in INIT step. This is done for concurrency checks - the initial operation ID is null, so the client receives the operation hash after operation registration in INIT authentication method instead of having the operation hash from the very beginning.
=> Fix #224: Error when initiating operation with unset operation ID 

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java, powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties, powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties
Concurrency check needs to be bypassed for Mobile API (it makes no sense there). So when operation hash is missing, concurrency check is skipped.
=> Fix #227: Invalid operation in authorize endpoint of Mobile API

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/PushRegistrationController.java
Little less destructive fix. I have moved push message registration to separate controller, with simpler API endpoint. Also, I have kept the operation list endpoint authenticated with signature, I just changed the endpoint name there.
=> Fix #208: Implement possession signed endpoints with using token based authentication

powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java, powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/BankAccountListRequest.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/api/DataAdapter.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/BankAccountController.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/service/DataAdapterService.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/validation/CreateSMSAuthorizationRequestValidator.java, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/service/SMSPersistenceService.java, powerauth-data-adapter/src/main/resources/static/resources/messages_cs.properties, powerauth-data-adapter/src/main/resources/static/resources/messages_en.properties, powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java
Support for 2FA login in Data Adapter
Do not send bank account details for non-payment operations
=> Fix #236: SMS message validator should be action independent

powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/response/ServiceStatusResponse.java, powerauth-data-adapter/pom.xml, powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/ServiceController.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/ServiceStatusResponse.java, powerauth-nextstep/pom.xml, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ServiceController.java, powerauth-webflow-client/pom.xml, powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/controller/ServiceController.java, powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/model/ServiceStatusResponse.java, powerauth-webflow/pom.xml, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/ServiceController.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/model/ServiceStatusResponse.java
This is a quick addition of the version and compilation time. I would like to postpone the refactoring of placing service status API code into a library after the release. Right now there are few lines of duplicate code, but I don't think this is a problem now.
=> Fix #262: Add version and compilation time to service status endpoint

powerauth-webflow-client/src/main/resources/templates/layout.html, powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties, powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties, powerauth-webflow/package.json, powerauth-webflow/src/main/js/client.js, powerauth-webflow/src/main/js/websocket-client.js, powerauth-webflow/src/main/resources/templates/index.html
This PR resolves following items:
* Missing Intl support in IE9, IE10 and other retarded browsers - intl added as a library
* Fixed broken SockJS fallback in IE9 which was opening new windows when connecting - Web Sockets are now disabled in IE < 11
* Updated compatibility meta tag X-UA-Compatible for IE hints
* Warning message for users of IE 8 or older IE browsers which can be updated in I18N messages
=> Fix #260: Test and fix issues with IE9 and IE10

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
We need to allow operations to be valid in status FAILED/CANCELED in order to display a message about canceled operation when operation gets canceled in Mobile Token app.
=> Fix #276: Invalid message for operation canceled on mobile device

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
Added error and error_description query parameters when operation is canceled by user.
=> Fix #302: Invalid error handling during OAuth 2.0 handshake

powerauth-data-adapter/pom.xml, powerauth-webflow-authentication-form/pom.xml, powerauth-webflow-authentication-init/pom.xml, powerauth-webflow-authentication-mtoken/pom.xml, powerauth-webflow-authentication-operation-review/pom.xml, powerauth-webflow-authentication-sms/pom.xml, powerauth-webflow-authentication/pom.xml, powerauth-webflow-i18n/pom.xml, powerauth-webflow-resources/pom.xml, powerauth-webflow/pom.xml
We need to fix this in order to automatically release the correct libraries, not our internals.
=> Fix #328: Fix pom.xml files to release only the public artifacts

powerauth-mtoken-model/src/main/java/io/getlime/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java, powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/exception/OperationAlreadyCanceledException.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/MobileApiExceptionResolver.java, powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java
Fix includes:
* Fixed incorrect validation logic for next steps (validation should be only done for result = AuthResult.CONTINUE)
* Added specific Exception for case when canceled operation is being updated - OperationAlreadyCanceledException, this Exception is exported in Mobile Token API
* Added missing user IDs into cancelAuthorization calls (when user canceled the operation, the userId was changed to null in database, so information about previously authenticated user was lost)
=> Fix #354: REST API returns 500 when operation is already processed

powerauth-webflow/pom.xml
I excluded the `tomcat-embed-websocket` artifact in main pom.xml, there is no class conflict anymore and Web Flow runs on Wildfly AS.
=> Fix #362: Web Flow does not start on Wildfly AS

docs/sql/mysql/initial_data.sql, docs/sql/oracle/initial_data.sql
Here is the migration guide for this change:
https://github.com/lime-company/powerauth-webflow/wiki/Web-Flow-0.20.0#db-migration-to-bcrypt
=> Fix #369: Fix default client credentials to use bcrypt

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/MobileApiExceptionResolver.java
Added an extra handler for the specific exception type.
After checking with mobile team, we do not need to introduce a new error code.
=> Fix #383: Unable to cancel operation on mobile token in case of timeout

powerauth-mtoken-model/src/main/java/io/getlime/security/powerauth/lib/mtoken/model/entity/PartyInfo.java, powerauth-mtoken-model/src/main/java/io/getlime/security/powerauth/lib/mtoken/model/entity/attributes/Attribute.java, powerauth-mtoken-model/src/main/java/io/getlime/security/powerauth/lib/mtoken/model/entity/attributes/PartyAttribute.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/model/converter/AttributeConverter.java
I switch the PARTY_INFO attribute in mobile API from KEY_VALUE.
Remarks:
- The attribute name is PARTY_INFO, not PARTY to keep the enums synced accross different models.
- I don't see value in extending KeyValueAttribute for this attribute, because this would mean partial duplication of value and furthemore old version of mToken does not display PARTY_INFO attribute (the attribute is completely ignored and not displayed, so the value from KeyValueAttribute would be ignored). @petrdvorak if you feel we should extend KeyValueAttribute even under these circumstances let me know, I realize you wanted to do this for all new form data attributes.
New attribute in JSON response:
```
{
"type": "PARTY_INFO",
"id": "operation.partyInfo",
"label": "Application",
"partyInfo": {
"logoUrl": …
```
=> Fix #422: Enable PARTY_INFO attribute for mobile API

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/service/PushMessageService.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthMethodQueryService.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/PowerAuthWebServiceConfiguration.java
Migration to SOAP v3, see: https://github.com/wultra/powerauth-server/issues/175
Note that I still keep `io.getlime.powerauth.soap.v2` context path for JAXB marshaller, so that we can test v2 interfaces through webflow, otherwise we would get a JAXB error when using cmd-tool with webflow and PowerAuth version `2.0`.
=> Fix #434: Crypto 3.0: Versioning of web service interfaces

powerauth-mtoken-model/src/main/java/io/getlime/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/PushRegistrationController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/MobileApiExceptionResolver.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/exception/ActivationNotActiveException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/exception/ActivationNotConfiguredException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/exception/InvalidActivationException.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/service/PushMessageService.java
This PR fixes:
- Fix #439: Do not log invalid device as error for mobile token
- Added missing error handling (for various activation states)
- Better error messages (included activation ID in messages)
- Fixed obsolete comment for offline signature verification
=> Fix #439: Do not log invalid device as error for mobile token

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
Language is now set correctly without country suffix.
=> Fix #450: Invalid language in frontend vs. backend

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
The cancel redirect issue on Wildfly was caused by spaces in the redirect URL.
=> Fix #471: Cancel redirect does not work on Wildfly

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/model/converter/FormDataConverter.java
I unified the conversion logic with `OperationFormData.saveAttribute()`.
=> Fix #388: Mobile API returns multiple attributes with the same ID

powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java, powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/entity/DataAdapterError.java, powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/exception/NextStepServiceException.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java, powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/ApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/AuthStepException.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/CommunicationFailedException.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/OperationNotConfiguredException.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthMethodQueryService.java, powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties, powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/OAuth2AuthorizationServerConfiguration.java
This pull request contains following improvements related to error handling: 
- Fix #486: Do not expose service details when REST client fails
- Separated HTTP errors from JSON parsing errors
- Use user-friendly error messages instead of messages from Exceptions
- Do not throw Next Step exceptions in Web Flow
- Improved error handling
- Improved error logging
The new error screens are:
1. In case of communication errors with Data Adapter (service is down, a HTTP error occurs, unexpected non-JSON response with HTTP 200 status)
User authentication:
SMS authorization:
2. In case of communication errors with Next Step server (service is down, a HTTP error occurs, unexpected non-JSON response with HTTP 200 status)
Web Flow logs still contain all error details including HTTP status codes or …
=> Fix #486: Do not expose service details when REST client fails

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow/package-lock.json
Update of SOAP call of `verifyOfflineSignature`, signature types are determined based on the `allowBiometry` parameter.
=> Fix #507: Update SOAP call for offline verification

docs/Next-Step-Server-REST-API-Reference.md, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java
I added alternative `POST` methods for `DELETE` and `PUT` methods and documented them.
=> Fix #515: Provide alternatives for DELETE and PUT methods

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
This pull request backports the update of REST methods in Next Step. The Web Flow REST API changes were intentionally omitted. The documentation will be updated manually in developers portal, this branch does not have the `docs` folder yet.
=> Fix #517: Backport alternative methods for DELETE and PUT into branch 0.20.x

docs/Next-Step-Server-REST-API-Reference.md, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
This pull request backports the update of REST methods in Next Step. The Web Flow REST API changes were intentionally omitted. The documentation was updated in the `docs` folder and we will need to regenerate the developers portal documentation.
=> Fix #518: Backport alternative methods for DELETE and PUT into branch 0.21.x

docs/Web-Flow-0.22.0.md, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java, powerauth-webflow-authentication-consent/pom.xml, powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/controller/ConsentController.java, powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/model/request/ConsentAuthRequest.java, powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/model/response/ConsentAuthResponse.java, powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/model/response/ConsentInitResponse.java, powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/service/HtmlSanitizationService.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
I found several issues when testing consent screen with `POWERAUTH_TOKEN` step instead of `SMS_KEY`:
- Operation must not be returned in pending operations in case it was already processed (e.g. consent screen is displayed after `POWERAUTH_TOKEN` step)
- Removed invalid check for authentication method availability (the logic was broken but discovered only now that an additional step is available after `POWERAUTH_TOKEN`)
- Updated JavaDoc
- Added documentation of database changes
- Implemented HTML sanitization based on used policy in `sanitize-html` JavaScript project
=> Fixes from testing of consent screen

docs/sql/mysql/initial_data.sql, docs/sql/oracle/initial_data.sql
Added consent steps into SCA methods so that they can be easily tested and always part of the flow.
We can disable consent form dynamically on Data Adapter level, in case it becomes too annoying.
I also included 2 organizations for testing.
=> Fix #561: Add consent into SCA method steps

powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/controller/ConsentController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
Updated logic for init step of consent page, so that in `CONSENT` init call it is set what is the chosen authentication method. This is done because we do not write an empty record into operation history when an authentication method starts - chosen auth method is used for this purpose in case of SCA steps.
=> Fix #567: Invalid logic in getAuthMethodName for consent page

powerauth-webflow-resources/pom.xml, powerauth-webflow/pom.xml
Revert last moment dependency changes done by Snyk, there were OAuth client issues during testing related to redirect URL configuration, we'll update dependencies in next release
=> Revert last moment dependency changes done by Snyk

powerauth-webflow/src/main/js/components/securityOverride.js
An attemt to make the warning less ugly - original UI:
After removing the Jumbotron:
=> Fix #593: Improve Android warning UI

powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/controller/ConsentController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
This pull request cleans HTTP session when `/authenticate` endpoint is called as well as during various cases in regular operation processing in controllers.
The problem was found because the `INITIAL_MESSAGE_SENT` attribute remained in HTTP session when the same HTTP session was reused by multiple operations - the previous operation was interrupted and since the attribute was already set, the initial SMS was not sent.
=> Fix #601: Clean HTTP session properly

docs/Web-Flow-0.23.0.md, docs/sql/mysql/create_schema.sql, docs/sql/oracle/create_schema.sql, docs/sql/postgresql/create_schema.sql, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MessageController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/interceptor/WebSocketHandshakeInterceptor.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/repository/model/entity/OperationSessionEntity.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/OperationSessionService.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/WebSocketMessageService.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebSocketConfiguration.java
The client IP address is either resolved from `X-FORWARDED-FOR` HTTP header or from servlet request.
Note that the IP address may be IPv6. In this case `-Djava.net.preferIPv4Stack=true` needs to be set for the runtime, e.g. in Docker image or as an option for Tomcat.
=> Fix #655: AFS: Detect client IP address

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/interceptor/WebSocketHandshakeInterceptor.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebSocketConfiguration.java, powerauth-webflow/src/main/resources/application.properties
We have to handle the case when client is IPv6 behind a proxy which forwards the IPv6 address correctly, however AFS cannot handle it because it only supports IPv4. I added an option to enable forcing of IPv4 and fallback logic in case no IPv4 address could not be determined.
=> Fix #675: Filter IPv6 IP addresses when detecting client IP address

docs/Mobile-Token-Configuration.md, docs/Web-Flow-0.22.0.md, docs/sql/mysql/create_schema.sql, docs/sql/oracle/create_schema.sql, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetOperationConfigDetailResponse.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/converter/OperationConfigConverter.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationConfigEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/MobileTokenConfigurationService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-webflow-authentication-approval-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/approvalsca/controller/ApprovalScaInitController.java, powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/controller/LoginScaInitController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthMethodQueryService.java
This pull request contains following changes:
- Mobile token can now be configured on operation basis using table `ns_operation_config`, column `mobile_token_enabled`. The use case is when mobile token should be enabled for e.g. credit card payments but should be disabled for e.g. PSD2.
- I extended the usage of `ns_auth_method.has_mobile_token` to control not only pending operations, however it also controls whether mobile token is available for given authentication method.
- The existing mobile token configuration in `ns_user_prefs` which configures activation ID remains as before.
The pull request handles two use cases:
- SCA: the `/user/operation/list` endpoint (pending operations) filters out operations which do not have mobile token enabled for any of the 3 reasons mentioned above …
=> Mobile token configuration per operation

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
`MobileTokenOnlineController` has custom timeout handling due to sending of push messages, so the `cancelAuthorization` method needs to be called so that:
- Next Step operation status is updated
- Data Adapter is notified about operation change
- AFS receives information about operation timeout
=> Fix #533: Timed out operation is not updated in Next Step

docs/Web-Flow-0.23.0.md, docs/sql/mysql/create_schema.sql, docs/sql/oracle/create_schema.sql, docs/sql/postgresql/create_schema.sql, powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/GetMobileTokenConfigRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/UpdateMobileTokenRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetMobileTokenConfigResponse.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationHistoryEntity.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java, powerauth-webflow-authentication-approval-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/approvalsca/controller/ApprovalScaController.java, powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/controller/LoginScaController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthMethodQueryService.java
I fixed the issue, however I cannot test it properly because I don't have a USB-C to USB adaper / USB-C to lightning cable during my trip. So I just tested that the `mobile_token_active` value is written into the DB which should cause the pending operations endpoint start returning correct response at the right moment. I will test it more thoroughly tomorrow once I buy the cable.
=> Fix #699: Two-step selection of account breaks mobile token

powerauth-webflow-authentication-approval-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/approvalsca/controller/ApprovalScaController.java, powerauth-webflow-authentication-consent/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/consent/controller/ConsentController.java, powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java, powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/ApiController.java, powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/TimeoutController.java, powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/controller/LoginScaController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/MobileApiExceptionResolver.java, powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/OperationIsAlreadyCanceledException.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/OperationIsAlreadyFailedException.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/OperationIsAlreadyFinished.java
This pull reques contains following changes:
- Verification of operation expiration is centralized and it is moved it into validation of operation state. The `checkOperationExpiration()` method is private now.
- Operation expiration is checked before other validations to provide a friendly message for Mobile Token when the operation is expired instead of providing error with message about already failed operation (caused by another API call which validated the state). This fixes first part of the reported issue.
- The exception resolver was using incorrect exceptions (same class name, different package). I fixed the exception handling and translation of Next Step exceptions to Web Flow. I also renamed the conflicting exception classes. This fixes the second part of the issue - invalid …
=> Fix #705: Wrong expired error on mobile api

powerauth-webflow-resources/pom.xml
Spring OAuth introduced a deserialization error, the error is fixed in spring-security-oauth2 version `2.3.8`.
=> Fix #720: Not allowed to deserialize error

powerauth-webflow/src/main/js/components/login.js, powerauth-webflow/src/main/js/components/loginSca.js, powerauth-webflow/src/main/js/components/operationTimeout.js
This pull request resolves the issue with `<OperationTimeout/>` component present in multiple tabs when multiple organizations are used. Only one `<OperationTimeout>` component is active depending on the active organization. The issue manifested by duplicate timeout requests as well as 500 error when updating operation state.
=> Fix #603: Optimize timeout API requests

powerauth-webflow-client/src/main/resources/static/css/main.css, powerauth-webflow-client/src/main/resources/templates/home.html, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebFlowServerConfiguration.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java, powerauth-webflow/src/main/js/actions/consentActions.js, powerauth-webflow/src/main/js/components/app.js, powerauth-webflow/src/main/js/components/consent.js, powerauth-webflow/src/main/resources/application.properties, powerauth-webflow/src/main/resources/templates/index.html
When the consent HTML has more than configured number of characters a wide consent panel is displayed to allow better display of large consent texts.
=> Fix #596: Consent screen should allow longer consent texts

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
Please check improved verification of redirect parameters during request cancellation.
One question: should we also make `state` mandatory? It is optional in Spring OAuth.
=> Fix #758: Improve cancellation of OAuth request redirect

docs/sql/mysql/initial_data.sql, docs/sql/oracle/initial_data.sql, docs/sql/postgresql/initial_data.sql, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/enumeration/OperationCancelReason.java, powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/listener/WebSocketDisconnectListener.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/model/converter/OperationCancellationConverter.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/OperationCancellationService.java, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
This pull request adds cancelation of operations in Next Step in case of unexpected errors (e.g. JavaScript error in client). Operation cancellation and related events are also centralized into a dedicated service and existing cancelation code is rewired to call the new service.
Furthermore I added steps for canceling operations via Web Sockets and via timeout detection which use the `INIT` authentication method.
=> Fix #759: Cancel operation in Next Step in case of an error

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/OperationSessionService.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/WebSocketMessageService.java
HTTP session ID is checked when operation is initialized or continued.
I also tightened the bolts during Web Socket registration, Web Socket session can be registered only once.
=> Fix #769: Improve validation of operation against HTTP session ID

powerauth-nextstep/pom.xml, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/configuration/WebApplicationConfig.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java, powerauth-tpp-engine/pom.xml, powerauth-webflow-client/pom.xml, powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/configuration/WebApplicationConfig.java, powerauth-webflow/pom.xml, powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebMvcConfiguration.java
I have tested that the generated time format is the same as before in JSON: `2020-04-20T13:08:00+0000`.
=> Fix #754: Startup warning related to Joda-Time

docs/Web-Flow-Configuration.md, powerauth-nextstep/src/main/resources/application.properties, powerauth-webflow/src/main/resources/application.properties
I have commented out the `utf8mb4` charset setting. It was ignored by other DB engines, so I think no harm was done, but the setting was incorrect for sure.
=> Fix #792: Hibernate connection charset

docs/Next-Step-Server-REST-API-Reference.md, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/UpdateOperationResponse.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java
This pull request enriches the response from update operation, so that all relevant data is provided like in the case when creating an operation.
=> Fix #609: Operation update endpoint does not return operation data

pom.xml
Let's revert back to Java 8 for the source and target.
=> Fix #835: Set Maven Compiler Source And Target to 8

powerauth-webflow/src/main/resources/static/resources/css/base.css, powerauth-webflow/src/main/resources/static/resources/css/customization.css
The `panel-body` class is no longer used by `Panel` in React 16, so I switched the customization to the `panel-default` class. I visually compared the `0.24.1` version and the fix and they look the same.
=> Fix #917: Fix CSS issue after migration to React 16

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ApplicationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuditController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthenticationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialCounterController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialDefinitionController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialPolicyController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/HashConfigController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OrganizationController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OtpController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OtpDefinitionController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OtpPolicyController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/RoleController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ServiceController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/StepDefinitionController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/UserController.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OrganizationService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/RoleService.java, powerauth-nextstep/src/test/java/io/getlime/security/powerauth/app/nextstep/NextStepUserIdentityTest.java
I added `GET` method alternatives for REST API methods used for getting lists and details.
=> Fix #964: Provide GET alternatives in Next Step REST API

docs/sql/oracle/create_schema.sql, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialGenerationService.java
The `null` value for username needs to be used for credentials which have no usernames at all due to unique index constraint.
In Oracle multiple `null` values are not allowed in composite unique indexes. Thus, the unique index definition has to handle the `null` username case implicitly. A non-unique index for username was added for Oracle for performance reasons, too. 
In other supported databases multiple `null` values are allowed in composite unique indexes, so no DDL changes are required and the database queries correctly process both use cases (`null` usernames for PINs and `non-null` unique usernames for passwords).
=> Fix #987: Use null value in NO_USERNAME algorithm

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/CreateCredentialRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/CreateUserRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/ResetCredentialRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/UpdateCredentialRequest.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/UpdateUserRequest.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialService.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/UserIdentityService.java
I added the possibility to override credential expiration timestamp into all cases where credential expiration is handled.
=> Fix #994: Allow setting custom credential expiration for temporary credential migration

powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java, powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/controller/LoginScaController.java, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java, powerauth-webflow/src/main/resources/application.properties
This pull request implements credential type check. By default it is not possible to login using TEMPORARY credentials but it can be changed in configuration.
The implementation differs slightly for 2 cases:
- username and password authentication: authentication fails for TEMPORARY credentials
- SCA use case: fake SMS authentication page is presented to user for TEMPORARY credentials
In case Data Adapter proxy is enabled in Next Step the information about credential type is not available, the behaviour is the same as before, it is expected that system which performs the authentication does not allow it for TEMPORARY credentials if required.
=> Fix #997: Add option to disallow login with temporary credentials in Web Flow

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebSocketConfiguration.java
Spring Framework introduced a new method for Cors patterns: `setAllowedOriginPatterns`.
=> Fix #1012: Cors exception in Web Flow

docs/Web-Flow-1.1.0.md, pom.xml
I suggest we switch the source and target to Java 11. This will not only fix the Javadoc errors, but it will cause a migration to a new and better supported LTS version of Java.
Java 8 has gone through the End of Public Updates process for legacy releases, although commerical support is still available.
=> Fix #1034: Error while generating Javadoc

powerauth-nextstep/pom.xml, powerauth-tpp-engine/pom.xml, powerauth-webflow-client/pom.xml, powerauth-webflow/pom.xml
This change should resolve any future questions about the Log4J dependencies included in Spring logging.
=> Fix #1063: Exclude log4j-api dependency

pom.xml, powerauth-data-adapter-client/pom.xml, powerauth-data-adapter-model/pom.xml, powerauth-mtoken-model/pom.xml, powerauth-nextstep-client/pom.xml, powerauth-nextstep-model/pom.xml, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/BankAccountDetail.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/CredentialValue.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/EnableMobileTokenResult.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/OtpValue.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/PartyInfo.java, powerauth-nextstep/pom.xml, powerauth-tpp-engine-client/pom.xml, powerauth-tpp-engine-model/pom.xml, powerauth-tpp-engine/pom.xml, powerauth-webflow-authentication-approval-sca/pom.xml, powerauth-webflow-authentication-consent/pom.xml, powerauth-webflow-authentication-form/pom.xml, powerauth-webflow-authentication-init/pom.xml, powerauth-webflow-authentication-login-sca/pom.xml, powerauth-webflow-authentication-mtoken/pom.xml, powerauth-webflow-authentication-operation-review/pom.xml, powerauth-webflow-authentication-sms/pom.xml, powerauth-webflow-authentication/pom.xml, powerauth-webflow-client/pom.xml, powerauth-webflow-i18n/pom.xml, powerauth-webflow-resources/pom.xml, powerauth-webflow/pom.xml
Add missing `@NoArgsConstructor` annotations in model which solve serialization issues.
=> Fix #1069: Missing @NoArgsConstructor annotations in model

pom.xml, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthenticationService.java, powerauth-tpp-engine-model/pom.xml, powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java
Support for JDK 8, thanks to @saalistaja.
I suggest we merge it to `1123-payment-signing` branch, unfortunately there are still clients who insist on JDK 8.
=> Allow targeting to JDK 8

powerauth-tpp-engine-model/pom.xml, powerauth-tpp-engine-model/src/main/java/io/getlime/security/powerauth/app/tppengine/model/certificate/ICACertificateParser.java, powerauth-webflow/pom.xml
Fixed deprecation and suppression warning, Java 8 is now used as default everywhere.
=> Migrate to X500Name, code cleanup for Java 8

powerauth-data-adapter-client/pom.xml, powerauth-nextstep-client/pom.xml, powerauth-webflow-authentication-approval-sca/pom.xml, powerauth-webflow-authentication-consent/pom.xml, powerauth-webflow-authentication-form/pom.xml, powerauth-webflow-authentication-init/pom.xml, powerauth-webflow-authentication-login-sca/pom.xml, powerauth-webflow-authentication-mtoken/pom.xml, powerauth-webflow-authentication-operation-review/pom.xml, powerauth-webflow-authentication-sms/pom.xml, powerauth-webflow-authentication/pom.xml, powerauth-webflow-client/pom.xml
Just a clean up, may be postponed after release.
=> Fix #1145: Simplify exclusion of tomcat dependency

docs/Web-Flow-Installation-Manual.md
Fix #1462
In the manual, there is download link to Tomcat 9. The link was changed to point to Tomcat 10.
=> Fix #1462: Update documentation regarding AS support

docs/Deploying-Wildfly.md, pom.xml, powerauth-nextstep/pom.xml, powerauth-nextstep/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, powerauth-webflow/pom.xml, powerauth-webflow/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
Let's merge it to 1.6.0-SNAPSHOT
=> Fix #1441: Filter jboss descriptor with bouncycastle version from pom

pom.xml, powerauth-nextstep/pom.xml, powerauth-tpp-engine/pom.xml, powerauth-webflow-authentication-consent/pom.xml, powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/interceptor/WebSocketHandshakeInterceptor.java, powerauth-webflow-authentication/src/test/java/io/getlime/security/powerauth/lib/webflow/authentication/interceptor/WebSocketHandshakeInterceptorTest.java, powerauth-webflow/pom.xml
Guava dependency remains because of owasp-java-html-sanitizer, but the API not directly used anymore.
=> Fix #1535: Remove Guava dependency

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/error/response/CredentialValidationErrorResponse.java, powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/error/response/ExtendedErrorResponse.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java
Instead of propagating generic error response only:
```yml
"400":
description: "Invalid request, error codes: REQUEST_VALIDATION_FAILED, OPERATION_NOT_FOUND, OPERATION_NOT_VALID"
content:
application/json:
schema:
$ref: "#/components/schemas/ErrorResponse"
```
We now get following struture:
```yml
"400":
description: "Invalid request, error codes: REQUEST_VALIDATION_FAILED, OPERATION_NOT_FOUND, OPERATION_NOT_VALID"
content:
application/json:
schema:
oneOf:
- $ref: "#/components/schemas/ExtendedErrorResponse"
- $ref: "#/components/schemas/ErrorResponse"
- $ref: "#/components/schemas/CredentialValidationErrorResponse"
```
Which propagets also the `CredentialValidationError` itself, together with the enum `validationFailures`, as requested.
=> Fix #1762: NextStep: Swagger update for validationFailures error handling

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/configuration/OpenApiConfiguration.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/configuration/SecurityConfig.java, powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ServiceController.java
When the Next Step is configured with `powerauth.nextstep.security.auth.type=OIDC`, it is expected an access token is included in the request header. This PR enhances the generated swagger, when the auth type is set to OIDC as follows:
```yaml
security:
- bearerAuth: []
components:
securitySchemes:
bearerAuth:
type: http
scheme: bearer
bearerFormat: JWT
```
In case of `powerauth.nextstep.security.auth.type=NONE` (by default), no change is visible.
=> Fix #1765: NextStep: Missing securitySchemes in swagger
