wultra/powerauth-webflow

powerauth-webauth/pom.xml
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/PowerAuthWebAuthApplication.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/ServletInitializer.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/configuration/WebSocketConfiguration.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/controller/HomeController.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/controller/MessageController.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/model/entity/RegistrationMessage.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/repository/SessionRepository.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/repository/model/Session.java
powerauth-webauth/src/main/resources/application.properties
powerauth-webauth/src/main/resources/templates/index.html

Added dependency on 'spring-boot-starter-web'.
Implemented the new 'ServletInitializer' class.
Changed absolute paths to relative.
Updated project package name.
Changed the application class name to 'PowerAuthWebAuthApplication'.
Removed unused property from 'application.properties' file.
Removed static imports.
Changed website title.

Fix #3: Make the application runnable inside the container

---

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/enumeration/OperationRequestType.java
powerauth-nextstep/pom.xml
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/OperationHistoryRepository.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/OperationRepository.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/StepDefinitionRepository.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationEntity.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationHistoryEntity.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/StepDefinitionEntity.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/IdGeneratorService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java
powerauth-nextstep/src/main/resources/application.properties
powerauth-webauth-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/method/init/ApiController.java
powerauth-webauth-authentication/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/service/AuthenticationManagementService.java
powerauth-webauth-docs/sql/mysql/create_schema.sql
powerauth-webauth-docs/sql/mysql/initial_data.sql
powerauth-webauth/src/main/js/components/operation.js
powerauth-webauth/src/main/js/dispatcher/dispatcher.js
powerauth-webauth/src/main/resources/static/resources/messages_cs.properties
powerauth-webauth/src/main/resources/static/resources/messages_en.properties

Added entities and repositories for operations, operation history and step definitions
Implemented dynamic step resolution based on step definitions loaded from database
Created new folder powerauth-webauth-docs for schema SQL and documentation
Fix of #21 - the problem was in string comparison
Localization of operation review step

Implementation of issue #19 - Implement dynamic step resolution logic

---

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetOperationDetailResponse.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/OperationEntity.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java

Implementation of #35 - Return next steps in operation detail REST service

---

powerauth-credential-server-sample/src/main/java/io/getlime/security/powerauth/lib/credentials/exception/DefaultExceptionResolver.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java
powerauth-webauth/src/main/java/io/getlime/security/powerauth/app/webauth/exception/DefaultExceptionResolver.java

Fix #38: Use Logger to log exceptions

---

powerauth-webauth/src/main/js/components/token.js

Potential race condition in the authenticate() method calls is handled
I tested both WebSocket authorization and 3s polling, both work fine.

Fix #58: Authorization notification using WebSockets vs. regular authentication in mtoken step

---

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/AuthMethodDetail.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetAuthMethodsResponse.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/model/entity/AuthMethodEntity.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthMethodService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java
powerauth-webauth-docs/sql/mysql/create_schema.sql
powerauth-webauth-docs/sql/mysql/initial_data.sql
powerauth-webauth/src/main/resources/static/resources/messages_cs.properties
powerauth-webauth/src/main/resources/static/resources/messages_en.properties

Note that both DDL and initial data has changed.
Additional changes:
* Added the INIT method into the list of methods stored in the database.
* AuthMethodDetail now returned in services, the response includes hasUserInterface and displayNameKey fields.
* OperationController split into two controllers, separating operations and authentication methods / user preferences.

Fix #43: Add displayable attributes to auth methods.

---

powerauth-webauth-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webauth/authentication/sms/controller/SMSAuthorizationController.java

Use HTTP Session for storing the messageId

Refactoring to Bank Adapter for SMS authorization controller

---

powerauth-webflow-client/pom.xml
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/configuration/OAuth2ConnectConfiguration.java
powerauth-webflow-client/src/main/resources/application.properties

Use in-memory H2 DB
Allow launching via 'java -jar' command

Fix #118: Make the demo app more independent

---

powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/api/DataAdapter.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/AuthenticationController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/BankAccountController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/FormDataChangeController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/SMSAuthorizationController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/exception/DefaultExceptionResolver.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/service/DataAdapterService.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/service/OperationFormDataService.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/validation/AuthenticationRequestValidator.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/validation/CreateSMSAuthorizationRequestValidator.java
powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/FormLoginController.java
powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java

Business logic is isolated. We can discuss how to further separate implementation code for the 3rd party, for now I placed client specific code into the 'impl' package.

Fix #107: Isolate business logic of Data Adapter into separate service

---

powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/SMSAuthorizationController.java

Wrong validator used in SMS controller.

Fix #139: ClassCastException in DataAdapter validation

---

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/UpdateAuthMethodRequest.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthMethodService.java

Fix #154: Simplify JSON for auth method configuration

---

powerauth-webflow-client/src/main/resources/templates/home.html

I just forgot to put the value in client HTML form.

Fix #164: Due date value is missing

---

powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/ApiController.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/model/request/InitOperationRequest.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/model/response/InitOperationResponse.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthMethodQueryService.java
powerauth-webflow/src/main/js/actions/startHandshakeActions.js
powerauth-webflow/src/main/js/components/startHandshake.js
powerauth-webflow/src/main/js/dispatcher/dispatcher.js

 Fix #170: Invalid response data in /api/auth/init/authenticate

---

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/ActivationNotActiveException.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/ActivationNotAvailableException.java
powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties
powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties

See #166 for different status messages sent in push message body.

Fix #166: Send push message when operation is finished

---

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/MessageTranslationService.java

Currenty we use following messages:
MISSING_LOCALIZATION_FOR_FIELD: i18n_key
MISSING_VALUE_FOR_FIELD: i18n_key
The reason for all caps is to help not to overlook the missing key. I can change the message to anything else if this is too ugly.

Fix #189: Do not crash on missing localization key with value substitutes

---

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java

Leverage number of remaining attempts from PA, it may be lower than number of remaining attempts from Next Step

Leverage number of remaining attempts from PA

---

powerauth-webflow-client/src/main/resources/templates/home.html
powerauth-webflow-client/src/main/resources/templates/layout.html
powerauth-webflow/src/main/resources/templates/index.html
powerauth-webflow/src/main/resources/templates/oauth/error.html

I added the viewport meta tag. I found a recommendation to use width=device-width instead of a fixed width, but if you have better experience with fixed with we can change it. I didn't limit the scaling so that users can scale manually on smaller devices.

Fix #242: Optimize display for mobile devices

---

powerauth-webflow-resources/src/main/java/io/getlime/security/powerauth/lib/webflow/resource/configuration/WebFlowResourcesServerConfiguration.java
powerauth-webflow-resources/src/main/java/io/getlime/security/powerauth/lib/webflow/resource/controller/UserProfileController.java
powerauth-webflow-resources/src/main/java/io/getlime/security/powerauth/lib/webflow/resource/model/UserResponse.java

I implemented the enhancement. Post-release we should refactor the common service status code to a shared project (as already discussed), for now I placed the code into powerauth-webflow-resources project.
See response below:

Fix #266: Add information about the server to connection info

---

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java

The operation is verified before initiating the authentication process.
Note that we display the default error message which doesn't include any details why the error occurred. Let me know in case we want to improve the error message, we can differentiate the different error states, too.

Fix #246: Cancel the operation in case invalid operation_id is provided

---

pom.xml
powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/BankAccountListRequest.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/OperationChangeNotificationRequest.java
powerauth-data-adapter/pom.xml
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/api/DataAdapter.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/exception/DefaultExceptionResolver.java
powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/OperationFormData.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/attribute/OperationFormFieldAttribute.java
powerauth-nextstep/pom.xml
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/QRCodeExceptionResolver.java
powerauth-webflow-authentication/pom.xml
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/AuthenticationExceptionResolver.java
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow/pom.xml
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/exception/DefaultExceptionResolver.java

This PR also contains fix of #94 so that no warnings are printed on Java 9, too.

Fix #293: Fix JavaDoc

---

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java
powerauth-webflow/src/main/js/components/error.js

PR also includes minor Exception cleanup.

Fix #297: Broken message after UI redesign

---

powerauth-webflow/src/main/resources/static/resources/css/base.css
powerauth-webflow/src/main/resources/static/resources/css/customization.css
powerauth-webflow/src/main/resources/templates/index.html
powerauth-webflow/src/main/resources/templates/oauth/error.html

Split CSS to base.css and customization.css

Fix #306: Use `word-wrap` CSS attribute on operation values

---

powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/entity/FormDataChange.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/AuthenticationRequest.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/response/DecorateOperationFormDataResponse.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/AuthenticationController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/FormDataChangeController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/OperationChangeController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/SMSAuthorizationController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/controller/ServiceController.java
powerauth-data-adapter/src/main/java/io/getlime/security/powerauth/lib/dataadapter/impl/service/DataAdapterService.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/OperationFormData.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ServiceController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java
powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/ApiController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/PushRegistrationController.java
powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java
powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/AuthenticationExceptionResolver.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthenticationManagementService.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/PowerAuthWebServiceConfiguration.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/ServiceController.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/exception/DefaultExceptionResolver.java

I added logging into all controllers and some of the important services. 
In some cases I had to change level from INFO to FINE to avoid spamming the log.

Fix #317: Improve logging of Web Flow

---

powerauth-webflow/package.json
powerauth-webflow/src/main/js/components/login.js
powerauth-webflow/src/main/js/components/operationDetail.js
powerauth-webflow/src/main/js/components/operationReview.js
powerauth-webflow/src/main/js/components/smsAuth.js
powerauth-webflow/src/main/js/components/startHandshake.js
powerauth-webflow/src/main/js/components/tokenAuth.js
powerauth-webflow/src/main/js/components/tokenAuthOffline.js
powerauth-webflow/src/main/js/websocket-client.js

Additional changes:
* Removed JavaScript console log messages
* Updated spinner dependency to avoid react warnings
* Updated package.json metadata

Fix #349: Disable Stomp.js logging

---

powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/entity/AuthorizationCode.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/entity/DataAdapterError.java

Partial fix, more changes are in PR: https://github.com/lime-company/powerauth-webflow-customization/pull/20

Fix #315: Extract operation specific code in DA into separate methods

---

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/MobileApiExceptionResolver.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/AuthenticationExceptionResolver.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/exception/DefaultExceptionResolver.java

Fix #320: Avoid using 50X HTTP status codes in favor of 40X codes

---

pom.xml
powerauth-data-adapter-client/pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-mtoken-model/pom.xml
powerauth-nextstep-client/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-webflow-authentication-form/pom.xml
powerauth-webflow-authentication-init/pom.xml
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-operation-review/pom.xml
powerauth-webflow-authentication-sms/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow-resources/pom.xml
powerauth-webflow/package.json
powerauth-webflow/pom.xml
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java

This pull requests backports fix of issue #450 to the `0.20.0` release, the hotfix release version is `0.20.1`.
I updated versions of all `powerauth-webflow` components. I didn't create a new release of `powerauth-webflow-customization`, it does not seem to be required.

Hotfix release 0.20.1

---

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/ApiController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOfflineController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileTokenOnlineController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/service/PushMessageService.java
powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java
powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SMSAuthorizationController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java

This pull request contains following improvements:
- Fix #472: Inconsistent handling of PushServerClientException
- Removed obsolete new String[]{...} in logging

Fix #472: Inconsistent handling of PushServerClientException

---

pom.xml
powerauth-data-adapter-client/pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-mtoken-model/pom.xml
powerauth-nextstep-client/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-webflow-authentication-form/pom.xml
powerauth-webflow-authentication-init/pom.xml
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-operation-review/pom.xml
powerauth-webflow-authentication-sms/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow-resources/pom.xml
powerauth-webflow/package.json
powerauth-webflow/pom.xml
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/OAuth2AuthorizationServerConfiguration.java

This pull request contains following changes:
- Fix #428: Support for Java 11 
- Updated version to 0.22.0
- Updated Spring boot to 2.1.2.RELEASE
- Updated BC dependency

Fix #428: Support for Java 11 

---

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/OperationFormData.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/data/OperationAmountAttribute.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/data/OperationDataBuilder.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/validator/AmountValidator.java
powerauth-nextstep-model/src/test/java/io/getlime/security/powerauth/lib/nextstep/model/entity/data/OperationDataBuilderTest.java

Added validation for amount attribute.

Fix #420: Limit "amount" values to 2 decimal places

---

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/OperationFormData.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/data/OperationAmountAttribute.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/data/OperationDataBuilder.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/GetOperationConfigsRequest.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/response/GetOperationConfigsResponse.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/converter/OperationConfigConverter.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationConfigurationService.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java

This pull request contains following changes:
- Fix #419: Optimize operation config retrieval in getOperationListImpl
- Updated JavaDoc

Fix #419: Optimize operation config retrieval in getOperationListImpl

---

powerauth-webflow/package-lock.json
powerauth-webflow/package.json
powerauth-webflow/pom.xml
powerauth-webflow/webpack.config.js

Changes:
- Fix #209: Warning about deprecated babel preset [Jenkins]
- Updated JavaScript maven dependencies
- Added package-lock.json file

Fix #209: Warning about deprecated babel preset [Jenkins]

---

pom.xml
powerauth-data-adapter-client/pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-mtoken-model/pom.xml
powerauth-nextstep-client/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-webflow-authentication-form/pom.xml
powerauth-webflow-authentication-init/pom.xml
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-operation-review/pom.xml
powerauth-webflow-authentication-sms/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow-resources/pom.xml
powerauth-webflow/pom.xml

I increased component versions to `0.21.1` for the bugfix release.

Prepare release 0.21.1

---

pom.xml
powerauth-data-adapter-client/pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-mtoken-model/pom.xml
powerauth-nextstep-client/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-webflow-authentication-form/pom.xml
powerauth-webflow-authentication-init/pom.xml
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-operation-review/pom.xml
powerauth-webflow-authentication-sms/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow-resources/pom.xml
powerauth-webflow/pom.xml

I increased component versions to `0.20.2` for the bugfix release.

Prepare release 0.20.2

---

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java

I have added the `state` parameter, so that the processing after canceled request can identify which client sent the request.
See:
https://www.oauth.com/oauth2-servers/authorization/the-authorization-response
```
If the request contained a state parameter, the error response must also include the exact value from the request. The client may use this to associate this response with the initial request.
```

Fix #542: Add state parameter when operation is canceled

---

docs/Web-Flow-0.22.0.md

Wrong table definition, I forgot to merge this change.

Fix DDL for Oracle

---

powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/controller/TimeoutController.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/model/request/VerifyTimeoutRequest.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/model/response/VerifyTimeoutResponse.java
powerauth-webflow-authentication-init/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/init/service/TimeoutInformationService.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java
powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties
powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties
powerauth-webflow/src/main/js/actions/timeoutActions.js
powerauth-webflow/src/main/js/components/consent.js
powerauth-webflow/src/main/js/components/error.js
powerauth-webflow/src/main/js/components/login.js
powerauth-webflow/src/main/js/components/loginSca.js
powerauth-webflow/src/main/js/components/operationDetail.js
powerauth-webflow/src/main/js/components/operationReview.js
powerauth-webflow/src/main/js/components/operationTimeout.js
powerauth-webflow/src/main/js/components/smsAuth.js
powerauth-webflow/src/main/js/components/smsComponent.js
powerauth-webflow/src/main/js/components/success.js
powerauth-webflow/src/main/js/components/tokenAuth.js
powerauth-webflow/src/main/js/reducers/index.js
powerauth-webflow/src/main/js/reducers/timeoutReducer.js
powerauth-webflow/src/main/resources/application.properties
powerauth-webflow/src/main/resources/static/resources/css/base.css

This pull request contains following changes:
- Implementation of timeout warning and proactive checking of full timeout even if user does not send any request
- Changed order of password and SMS authorization code in SCA credentials verification
- Updated look of banners

Fix #552: Implement timeout warning

---

powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/enumeration/SmsDeliveryResult.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/response/CreateSmsAuthorizationResponse.java
powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/SmsDeliveryFailedException.java
powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties
powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties
powerauth-webflow/src/main/js/actions/smsAuthActions.js
powerauth-webflow/src/main/js/components/smsAuth.js
powerauth-webflow/src/main/js/components/tokenAuthSms.js

- Fix #578: SMS delay enforcement during language switch or page refresh
- Fix #575: Improve response object for SMS delivery

Update SMS handling for SCA

---

powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/model/HttpSessionAttributeNames.java

Limit sending to only once per SMS step, other SMSes are sent on user request.

Fix #583: Send SMS automatically only once per step

---

powerauth-webflow-authentication-form/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/form/controller/FormLoginController.java
powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/controller/HomeController.java

- Improve logging for password protection
- Allow other operation names than expected ones (@kober32 please see this change, we need to support other operation names)

Minor changes from snapshot testing

---

powerauth-webflow/src/main/js/components/consent.js

Minor consent issue found during testing, the option value should be always set.

Set value for not checked consent options

---

powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/controller/HomeController.java
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/model/OperationForm.java
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/model/PaymentForm.java
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/model/ScaForm.java
powerauth-webflow-client/src/main/resources/static/css/main.css
powerauth-webflow-client/src/main/resources/templates/home.html

Added fields in demo client for application context editing.
---

Editable application context in client

---

powerauth-webflow/.snyk
powerauth-webflow/package-lock.json
powerauth-webflow/package.json

This fix removes the Snyk patch and updates to version of `lodash` which fixes the vulnerability.

Fix #605: Fix security issues reported by GitHub

---

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/interceptor/WebSocketHandshakeInterceptor.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebSocketConfiguration.java
powerauth-webflow/src/main/resources/application.properties

As per request from the client, we will make it possible to disable client IP address detection.

Fix #677: AFS: configuration of IP address detection

---

docs/Basic-Definitions.md
docs/Components.md
docs/Customizing-Operation-Form-Data.md
docs/Data-Adapter-REST-API-Reference.md
docs/Data-Adapter.md
docs/Database-Table-Structure.md
docs/Next-Step-Server-REST-API-Reference.md
docs/Next-Step-Server.md
docs/Readme.md
docs/Web-Flow-0.23.0.md
docs/Web-Flow-Configuration.md
powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java
powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AfsIntegrationService.java
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/controller/HomeController.java

Update of Web Flow documentation, mainly regarding the AFS implementation.

Update Web Flow documentation

---

powerauth-webflow/src/main/js/websocket-client.js

This pull request fixes reason why operation timeout fails when web socket calls fail (root cause).

Fix #721: Catch Web Socket errors

---

powerauth-webflow-client/src/main/resources/application.properties

An incompatibility was introduced in Spring boot `2.2.0`.

Fix #737: Logout not working in WebFlow client

---

powerauth-webflow/src/main/js/actions/consentActions.js

Fixed JavaScript error when consent is skipped due to missing callback.

Fix #741: Error when consent is skipped

---

powerauth-webflow/src/main/js/components/approvalSca.js
powerauth-webflow/src/main/js/components/consent.js
powerauth-webflow/src/main/js/components/smsComponent.js
powerauth-webflow/src/main/js/components/tokenAuthOffline.js
powerauth-webflow/src/main/resources/static/resources/css/base.css

I rearranged the buttons as discussed so that they are placed horizontally next to each other.

 Fix #745: Rearrange action buttons for UI consistency

---

powerauth-webflow/src/main/js/components/approvalSca.js
powerauth-webflow/src/main/js/components/consent.js
powerauth-webflow/src/main/js/components/operationReview.js
powerauth-webflow/src/main/js/components/smsAuth.js
powerauth-webflow/src/main/js/components/tokenAuth.js

Added missing initialization parameter.

Fix #761: Timeout warning not initialized

---

powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/controller/LoginScaController.java
powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties
powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties

Improved error messages when validating the `username` field.

Fix #733: Improve validation error message

---

powerauth-webflow-client/src/main/resources/templates/home.html

Fix #763: WebFlow client sends CSRF twice

---

pom.xml
powerauth-data-adapter-client/pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-mtoken-model/pom.xml
powerauth-nextstep-client/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-tpp-engine-client/pom.xml
powerauth-tpp-engine-model/pom.xml
powerauth-tpp-engine/pom.xml
powerauth-webflow-authentication-approval-sca/pom.xml
powerauth-webflow-authentication-consent/pom.xml
powerauth-webflow-authentication-form/pom.xml
powerauth-webflow-authentication-init/pom.xml
powerauth-webflow-authentication-login-sca/pom.xml
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-operation-review/pom.xml
powerauth-webflow-authentication-sms/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow-resources/pom.xml
powerauth-webflow/pom.xml

I increased the version to prepare the next hotfix release.

Update version to 0.23.2

---

powerauth-webflow/package-lock.json

Fix #796: Fix packages-lock.json

---

docs/Web-Flow-Configuration.md
powerauth-nextstep/src/main/resources/application.properties
powerauth-tpp-engine/src/main/resources/application.properties
powerauth-webflow-client/src/main/resources/application.properties
powerauth-webflow/src/main/resources/application.properties

Changes based on Spring boot 2.2 migration guide.

Fix #739: Update application configuration

---

powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/enumeration/CertificateAuthenticationMode.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/CreateSmsAuthorizationRequest.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/DecorateOperationFormDataRequest.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/request/InitAuthMethodRequest.java
powerauth-data-adapter-model/src/main/java/io/getlime/security/powerauth/lib/dataadapter/model/response/InitAuthMethodResponse.java
powerauth-webflow-authentication-approval-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/approvalsca/controller/ApprovalScaController.java
powerauth-webflow-authentication-approval-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/approvalsca/model/response/ApprovalScaInitResponse.java
powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/controller/LoginScaController.java
powerauth-webflow-authentication-login-sca/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/loginsca/model/response/LoginScaInitResponse.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java
powerauth-webflow-authentication-operation-review/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/method/operation/controller/OperationReviewController.java
powerauth-webflow-authentication-sms/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/sms/controller/SmsAuthorizationController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/AuthMethodResolutionService.java
powerauth-webflow-i18n/src/main/resources/static/resources/messages_cs.properties
powerauth-webflow-i18n/src/main/resources/static/resources/messages_en.properties
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/SecurityConfiguration.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/TlsClientController.java
powerauth-webflow/src/main/js/components/loginSca.js
powerauth-webflow/src/main/js/reducers/dispatchingReducer.js
powerauth-webflow/src/main/resources/application.properties
powerauth-webflow/src/main/resources/static/resources/css/base.css

The pull request currently contains only backend changes. I am still working on the UI.
To be reviewed together with:
https://github.com/wultra/powerauth-webflow-customization/pull/129

Authentication method configuration and certificate updates

---

docs/sql/mysql/initial_data.sql
docs/sql/oracle/create_schema.sql
docs/sql/oracle/initial_data.sql
docs/sql/postgresql/create_schema.sql
docs/sql/postgresql/initial_data.sql

Minor cleanup of DDL and initial data.

Set mobile_token_enabled defaults implicitly, fix DDL

---

docs/Compilation,-Packaging-and-Deployment.md
pom.xml
powerauth-tpp-engine-model/pom.xml
powerauth-webflow/pom.xml

I fixed the Java 11 Javadoc errors, however the settings are incompatible with Java 8, so I upgraded required runtime to Java 11.

 Fix #825: JavaDoc error during compilation

---

powerauth-webflow/package-lock.json
powerauth-webflow/src/main/js/actions/smsAuthActions.js
powerauth-webflow/src/main/js/components/offlineAuthCode.js
powerauth-webflow/src/main/js/components/smsComponent.js
powerauth-webflow/src/main/js/components/tokenAuthOffline.js
powerauth-webflow/src/main/js/components/tokenAuthOnline.js

Fix #867: Runaway promises in JS code

---

powerauth-webflow/package-lock.json
powerauth-webflow/package.json
powerauth-webflow/pom.xml
powerauth-webflow/webpack.config.js

This pull request completes the migration to webpack 5.

Migration to webpack 5

---

docs/Used-Push-Message-Extras.md

Specify which attributes are required, and under which circumstance.

Fix #915: Improve docs for mobile push message extras

---

powerauth-webflow/src/main/js/components/spinner.js
powerauth-webflow/src/main/resources/static/resources/css/base.css
powerauth-webflow/src/main/resources/static/resources/css/customization.css

The Spinner color can be customized, it is now white in Wultra customization:

Fix #610: Fix color of spinner in webflow

---

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/enumeration/CounterResetMode.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialCounterController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/repository/CredentialRepository.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java
powerauth-nextstep/src/test/java/io/getlime/security/powerauth/app/nextstep/NextStepAuthenticationTest.java

Updated logic for reseting soft counters based on more detailed requirements.

Fix #981: Update soft attempt counter reset logic

---

powerauth-data-adapter-client/src/main/java/io/getlime/security/powerauth/lib/dataadapter/client/DataAdapterClient.java
powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/ApplicationService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthMethodService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthenticationService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialCounterService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialDefinitionService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialHistoryService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialPolicyService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialProtectionService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/CredentialService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/HashConfigService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationConfigurationService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OperationPersistenceService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OrganizationService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OtpDefinitionService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OtpPolicyService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/OtpService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/RoleService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepDefinitionService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/UserAliasService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/UserContactService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/UserIdentityService.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/UserRoleService.java
powerauth-tpp-engine-client/src/main/java/io/getlime/security/powerauth/lib/tpp/engine/client/TppEngineClient.java

Additional logging:
- error codes from the REST API responses are logged by clients whenever they are available instead of generic HTTP errors
- additional INFO logs during authentication and for counter reset
- many new DEBUG messages throughout whole Next Step for easier debugging

Fix #967: Improve logging in Next Step

---

powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ApplicationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuditController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthMethodController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthenticationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialCounterController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialDefinitionController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialPolicyController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/HashConfigController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OperationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OrganizationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OtpController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OtpDefinitionController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/OtpPolicyController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/RoleController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/ServiceController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/StepDefinitionController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/UserController.java
powerauth-nextstep/src/main/resources/application.properties

Documentation of REST API:
- added summary for each method
- added HTTP status codes
- Next Step error code listed for HTTP status 400

Fix #1002: Add OpenAPI documentation for Next Step

---

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/request/OtpAuthenticationRequest.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/AuthenticationService.java
powerauth-nextstep/src/test/java/io/getlime/security/powerauth/app/nextstep/NextStepAuthenticationTest.java

For details of this change, see: https://github.com/wultra/powerauth-webflow/issues/1031

Fix #1031: OTP authentication in checkOnly mode

---

docs/Basic-Definitions.md
docs/Compilation,-Packaging-and-Deployment.md
docs/Components.md
docs/Configuring-Next-Step.md
docs/Data-Adapter-REST-API-Reference.md
docs/Database-Table-Structure.md
docs/Mobile-Token-Configuration.md
docs/Next-Step-Server-REST-API-Reference.md
docs/Next-Step-Server.md
docs/Web-Flow-Configuration.md
docs/Web-Flow-Installation-Manual.md
docs/_Sidebar.md
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/AuthenticationController.java
powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/controller/CredentialPolicyController.java

The documentation updates are almost done. Missing tasks:

Documentation updates for version 1.1.0

---

pom.xml
powerauth-data-adapter-client/pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-mtoken-model/pom.xml
powerauth-nextstep-client/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-tpp-engine-client/pom.xml
powerauth-tpp-engine-model/pom.xml
powerauth-tpp-engine/pom.xml
powerauth-webflow-authentication-approval-sca/pom.xml
powerauth-webflow-authentication-consent/pom.xml
powerauth-webflow-authentication-form/pom.xml
powerauth-webflow-authentication-init/pom.xml
powerauth-webflow-authentication-login-sca/pom.xml
powerauth-webflow-authentication-mtoken/pom.xml
powerauth-webflow-authentication-operation-review/pom.xml
powerauth-webflow-authentication-sms/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/controller/AuthMethodController.java
powerauth-webflow-client/pom.xml
powerauth-webflow-i18n/pom.xml
powerauth-webflow-resources/pom.xml
powerauth-webflow/pom.xml

Update of version and update of dependencies.

Fix #1065: Update version to 1.2.0

---

powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/BankAccountDetail.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/CredentialValue.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/EnableMobileTokenResult.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/OtpValue.java
powerauth-nextstep-model/src/main/java/io/getlime/security/powerauth/lib/nextstep/model/entity/PartyInfo.java

Add missing `@NoArgsConstructor` annotations in model which solve serialization issues.

Fix #1069: Missing @NoArgsConstructor annotations in model

---

powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/AuthenticationExceptionResolver.java
powerauth-webflow/src/main/js/actions/loginScaActions.js
powerauth-webflow/src/main/js/actions/smsAuthActions.js

One more UI bug found during testing of Docker images.

Fix #1072: Failed input validations not processed correctly

---

powerauth-tpp-engine-model/src/main/java/io/getlime/security/powerauth/app/tppengine/model/certificate/ICACertificateParser.java

This should help with compilation issues on various JDK versions.

Kill sun.security imports

---

pom.xml

Configure distribution management

---

powerauth-nextstep/pom.xml
powerauth-tpp-engine/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow/pom.xml

Configure publishing war

---

docs/Web-Flow-1.5.0.md
pom.xml
powerauth-data-adapter-model/pom.xml
powerauth-nextstep-model/pom.xml
powerauth-nextstep/pom.xml
powerauth-tpp-engine/pom.xml
powerauth-webflow-authentication/pom.xml
powerauth-webflow-client/pom.xml
powerauth-webflow/pom.xml

Let's merge it after https://github.com/wultra/powerauth-webflow/pull/1279

Fix #1278: Add PostgreSQL JDBC driver to war

---

powerauth-nextstep/src/test/java/io/getlime/security/powerauth/app/nextstep/configuration/NextStepClientFactory.java
powerauth-tpp-engine-client/src/main/java/io/getlime/security/powerauth/lib/tpp/engine/client/TppEngineClient.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java
powerauth-webflow-client/src/main/java/io/getlime/security/powerauth/app/webflow/demo/configuration/WebFlowServiceConfiguration.java

Depends on https://github.com/wultra/lime-java-core/pull/179 and https://github.com/wultra/powerauth-webflow/pull/1279

Fix #1285: Change configuration of ObjectMapper at RestClientConfiguration

---

powerauth-webflow/src/main/js/components/app.js
powerauth-webflow/src/main/resources/static/resources/css/customization.css

Added class for further styling. 
Base style of Flag selector set as draft

Fix #1351: Incorrect default color for language settings

---

docs/db/changelog/changesets/powerauth-webflow/1.4.x/20230324-audit.xml

- Remove the NOT NULL constraint in the liquibase changeset

Fix #1367: Invalid constraint for audit_type

---

.github/workflows/codeql-analysis.yml

Fix #1400: Add CodeQL Analysis

---

pom.xml
powerauth-webflow-authentication-mtoken/pom.xml

Fix #1406: Update dependencies

---

docs/Data-Adapter-REST-API-Reference.md

(cherry picked from commit 3f7069b7fab4c4872a72b954aa244cb3d864ca68)

Fix #1453: DocuCheck Warnings (backport)

---

docs/Web-Flow-Installation-Manual.md

(cherry picked from commit 5b919ced90218d584df6fcec768960401bb1ac85)

Fix #1462: Update documentation regarding AS support

---

powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/SecurityConfiguration.java

(cherry picked from commit 1124e6c31ef2cc21d26e62e5ab44ca0695c4c050)

Fix #1513: The request to non existent resource ends in 302

---

docs/sql/oracle/create_schema.sql
docs/sql/postgresql/create_schema.sql

(cherry picked from commit faf65bdb012af5055b998eeb974d6a1c65edb0f5)

Fix #1555: create_schema.sql in 1.6.0 branch is not valid

---

powerauth-nextstep-client/src/main/java/io/getlime/security/powerauth/lib/nextstep/client/NextStepClient.java

- Overload methods to accept request objects as much as possible.

Fix #1627: NextStepClient API improvements

---

powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MessageController.java
powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/controller/MobileAppApiController.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/configuration/WebFlowServicesConfiguration.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/listener/WebSocketDisconnectListener.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/websocket/WebSocketMessageService.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/websocket/WebSocketMessageServiceDummy.java
powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/service/websocket/WebSocketMessageServiceImpl.java
powerauth-webflow/pom.xml
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebFlowServerConfiguration.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/configuration/WebSocketConfiguration.java
powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java
powerauth-webflow/src/main/js/websocket-client.js
powerauth-webflow/src/main/resources/application.properties
powerauth-webflow/src/main/resources/templates/index.html

Backport to the `1.4.x` branch.

Fix #1668: Add configuration to disable websockets (#1669)

---

powerauth-webflow-i18n/src/main/java/io/getlime/security/powerauth/app/webflow/i18n/I18NService.java

(cherry picked from commit 07748e4eba080ffea981bc856629830933c956f0)

Fix #1348: Error while loading lang.json (backport)

---

docs/Next-Step-Server.md
docs/Web-Flow-Configuration.md

Fix #1174 Add OIDC, Encryption documentation for NextStep
(cherry picked from commit 792d909032b78756e07c77c0f47df32bad461edb)

Fix #1174 Add OIDC, Encryption documentation for NextStep (#1745)
